### ISSUE TITLE
the subpage builder does not trigger the create page hook

### ISSUE THREAD

**Issue by groenewege** [getkirby-v2/panel#571]
Hi,

When new pages are automatically created by the subpage builder, the `panel.page.create` hook does not get triggered for these pages.

This prevents my [auto-publish plugin](https://github.com/groenewege/kirby-auto-publish) from setting the visibility for these new pages.

Please consider changing this behaviour.

Thanks,
gunther

**Comment by bastianallgeier** [comment]
This is now solved on the develop branch.

**Comment by lukasbestle** [comment]
It looks like this issue is still there, see [this topic](https://forum.getkirby.com/t/subpage-builder-doesnt-call-hook/5262?u=lukasbestle).

**Comment by bastianallgeier** [comment]
Unfortunately this is quite complex. The hook isn't triggered a second time, to avoid infinite loops. But we would need smarter checks to allow the hook to be triggered a second time if it's not recursively called.
